# Generated by Django 4.2.17 on 2025-02-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_author_language_book_author_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['l_name']},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='L_name',
            new_name='l_name',
        ),
    ]
