# Generated by Django 4.2.17 on 2025-02-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_language_options_rename_l_name_language_l_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='l_name',
            new_name='name',
        ),
    ]
