# Generated by Django 4.2.17 on 2025-03-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_language_options_rename_l_name_language_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_views_all_borrowed_books', 'For Staff account Login can views all Borrowed Books'),)},
        ),
    ]
