# Generated by Django 4.2.17 on 2025-03-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='A_name',
            field=models.CharField(max_length=20),
        ),
    ]
