# Generated by Django 4.2.17 on 2025-03-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_author_a_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='A_name',
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='unknown author', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='unknown author', max_length=100),
        ),
    ]
