# Generated by Django 4.2.17 on 2025-03-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
