# Generated by Django 4.2.17 on 2025-03-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_remove_bookinstance_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
    ]
