# Generated by Django 4.2.17 on 2025-03-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_remove_bookinstance_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.book'),
        ),
    ]
